services:
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
      - ./secret:/secret
    environment:
      TZ: Europe/Stockholm
      WEBPASSWORD_FILE: /secret
    restart: unless-stopped
